# Generated by Django 5.2.6 on 2025-09-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabItem',
        ),
    ]
