# Generated by Django 5.2 on 2025-04-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('english_meaning', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('other_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
