# Generated by Django 5.2 on 2025-04-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_vocabitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabitem',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='other_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabitem',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
